sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BXbzj7ea7Ghci5lmZrRwqzppx9xbJJCgjd9XOsinOm/MAU4sC8XNeNOsaKb3FRusVLgitib2hMZ3+vCqW7tqB/TIMpijUiY7kZtWVEkGMkYs0r2g/niWJs4DvVOi0fE35xxYCy4xiU+AFl2+WNtmVQUfjYxlSDiNddonSa1Lrq2gcjOMhM3RYOw8M9SA8TNn4ffZcSjeD3aXxMa8WVDq+uSYIRFC95ZDIQu/e5yzyaF/tUmg9h5oRUMMoCxdTR0+LjGoSm2GR5cn91qroHRUtTiw4uarljub2eJ8xSx0EucihWYjjxv0Jhj/e59tDayZdgUbbNBwQ7MlOu290RIVT51Y36bHzeKuOMxOTnxfiFTmHqmTYHYDf6Eau9Do3Sxt8y9E9IQZvLqWer/oCHp9Z6ojhYdYV0CaSudJAVNMtT4h9b6kChB9HXJG6WL3LdmuC8hOt5qwZC74E9Sl+Enfwi3NiYcrKnGlKux92Uh6KCro2slMwKNr56Sxh14mkCJTqIGJKX/akY3IJqO5ksCKgKhhBnQBN2f0Fpc90JiyxvWUqZ/FmSEhLQc7a2Z5wYIk2u/Bfiif3Kzd6vhVCcHpn3s2G+3zwLolsUef4nCcyl8x8XvMg++gsSBnzrs1b+pP0Ab9BEbDW8w7q0fMapmi0B/ba+4d0d9qeX5Jh2PuGO0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Confessions-of-Jean-Jacques-Rousseau---Volume-03_3903
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy